pip install tensorflow/six-1.15.0-py2.py3-none-any.whl
pip install tensorflow/astunparse-1.6.3-py2.py3-none-any.whl
pip install tensorflow/cachetools-4.1.1-py3-none-any.whl
pip install tensorflow/certifi-2020.6.20-py2.py3-none-any.whl
pip install tensorflow/chardet-3.0.4-py2.py3-none-any.whl
pip install tensorflow/absl-py-0.9.0.tar.gz
pip install tensorflow/gast-0.3.3-py2.py3-none-any.whl
pip install tensorflow/google_pasta-0.2.0-py3-none-any.whl
pip install tensorflow/grpcio-1.31.0-cp36-cp36m-win_amd64.whl
pip install tensorflow/numpy-1.18.5-cp36-cp36m-win_amd64.whl
pip install tensorflow/h5py-2.10.0-cp36-cp36m-win_amd64.whl
pip install tensorflow/idna-2.10-py2.py3-none-any.whl
pip install tensorflow/Keras_Preprocessing-1.1.2-py2.py3-none-any.whl
pip install tensorflow/oauthlib-3.1.0-py2.py3-none-any.whl
pip install tensorflow/opt_einsum-3.3.0-py3-none-any.whl
pip install tensorflow/protobuf-3.13.0-cp36-cp36m-win_amd64.whl
pip install tensorflow/pyasn1-0.4.8-py2.py3-none-any.whl
pip install tensorflow/pyasn1_modules-0.2.8-py2.py3-none-any.whl
pip install tensorflow/setuptools-49.6.0-py3-none-any.whl
pip install tensorflow/tensorflow_estimator-2.3.0-py2.py3-none-any.whl
pip install tensorflow/termcolor-1.1.0.tar.gz
pip install tensorflow/urllib3-1.25.10-py2.py3-none-any.whl
pip install tensorflow/Werkzeug-1.0.1-py2.py3-none-any.whl
pip install tensorflow/wheel-0.35.1-py2.py3-none-any.whl
pip install tensorflow/wrapt-1.12.1.tar.gz
pip install tensorflow/zipp-3.1.0-py3-none-any.whl
pip install tensorflow/importlib_metadata-1.7.0-py2.py3-none-any.whl
pip install tensorflow/Markdown-3.2.2-py3-none-any.whl
pip install tensorflow/requests-2.24.0-py2.py3-none-any.whl
pip install tensorflow/requests_oauthlib-1.3.0-py2.py3-none-any.whl
pip install tensorflow/rsa-4.6-py3-none-any.whl
pip install tensorflow/google_auth-1.20.1-py2.py3-none-any.whl
pip install tensorflow/google_auth_oauthlib-0.4.1-py2.py3-none-any.whl
pip install tensorflow/scipy-1.4.1-cp36-cp36m-win_amd64.whl
pip install tensorflow/tensorboard_plugin_wit-1.7.0-py3-none-any.whl
pip install tensorflow/tensorboard-2.3.0-py3-none-any.whl
pip install tensorflow/tensorflow-2.3.0-cp36-cp36m-win_amd64.whl

